import {test, before, after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile, writeFile} from 'node:fs/promises';
import {createHash, randomUUID} from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import Stripe from 'stripe';
const endpoint='https://checkout.example';
const origin='http://localhost';
const secret='whsec_checkout_fixture_only';
const text='Fixture purchase terms for automated tests only. Perpetual rights to the licensed version.';
const terms={approved:true,version:'fixture-v1',sha256:createHash('sha256').update(text).digest('hex'),text,url:origin+'/terms/fixture-v1.html'};
const base={PURCHASES_ENABLED:'true',DELIVERY_ENABLED:'true',MODE:'test',SITE_ORIGIN:origin,STRIPE_SECRET_KEY:'sk_test_fixture_only',STRIPE_WEBHOOK_SECRET:secret,SINGLE_PRICE_ID:'price_single',TEAM_PRICE_ID:'price_team',TERMS_JSON:JSON.stringify(terms),ISSUER_JSON:JSON.stringify({name:'Fixture Merchant',address:'Fixture address',email:'issuer@example.com'}),TAX_POLICY:'none',LICENSED_VERSION:'fixture-version',OWNER_EMAIL:'owner@example.com',EMAIL_FROM:'Fixture Merchant <licenses@example.com>',EMAIL_API_KEY:'re_fixture_only'};
let bundle;
before(async()=>{const result=await build({stdin:{contents:"import Worker from './src/index'; export default class extends Worker {async fetch(r){if(new URL(r.url).pathname==='/__test_delivery'){await this.scheduled();return new Response('done');}return super.fetch(r);}}",resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,format:'esm',platform:'browser',external:['cloudflare:*'],loader:{'.ttf':'binary'}});bundle=result.outputFiles[0].text;});
const payment=(order,tier='single',overrides={})=>({id:'cs_test_'+order,object:'checkout.session',livemode:false,mode:'payment',payment_status:'paid',metadata:{order_id:order},status:'open',url:'https://checkout.stripe.com/c/pay/'+order,currency:'eur',amount_subtotal:tier==='single'?139900:469900,amount_total:tier==='single'?139900:469900,total_details:{amount_discount:0,amount_tax:0},line_items:{data:[{quantity:1,price:{id:'price_'+tier,currency:'eur',unit_amount:tier==='single'?139900:469900,livemode:false}}],has_more:false},customer_details:{email:'buyer@example.com',name:'Zoë Example — Тест'},payment_intent:{id:'pi_test_'+order,status:'succeeded',currency:'eur',amount_received:tier==='single'?139900:469900,latest_charge:{id:'ch_test_'+order,receipt_url:'https://pay.stripe.com/receipts/fixture'}},...overrides});
async function fixture(bindings={},sessionOverride={}) {
 const sent=[],requests=[]; let failEmails=0;
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundle,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{...base,...bindings},outboundService:async req=>{
  const url=new URL(req.url);requests.push({url:url.href,method:req.method});
  if(url.hostname==='api.stripe.com') {
   if(url.pathname.startsWith('/v1/prices/')) {const tier=url.pathname.includes('team')?'team':'single';return Response.json({id:'price_'+tier,object:'price',active:true,livemode:false,currency:'eur',unit_amount:tier==='single'?139900:469900,recurring:null});}
   if(req.method==='POST') {const body=new URLSearchParams(await req.text());requests.at(-1).body=body; const order=body.get('metadata[order_id]');return Response.json({id:'cs_test_'+order,status:'open',payment_status:'unpaid',url:'https://checkout.stripe.com/c/pay/'+order});}
   const order=url.pathname.split('/').at(-1).replace('cs_test_','');const row=await (await mf.getD1Database('DB')).prepare('SELECT tier FROM orders WHERE id=?').bind(order).first();return Response.json(payment(order,row?.tier,sessionOverride));
  }
  if(url.hostname==='api.resend.com') {const message=await req.json();sent.push({message,key:req.headers.get('Idempotency-Key')});if(failEmails-->0)return Response.json({error:'temporary'}, {status:503});return Response.json({id:'email_'+sent.length});}
  throw Error('Unexpected outbound request '+url);
 }}));
 const db=await mf.getD1Database('DB');await db.exec((await readFile('migrations/0001_checkout.sql','utf8')).replaceAll('\n',' '));
 const api=await mf.getWorker();
 const post=(path,body,headers={})=>api.fetch(endpoint+path,{method:'POST',headers:{Origin:origin,'content-type':'application/json',...headers},body:JSON.stringify(body)});
 const checkout=async(tier='single',id=randomUUID())=>{const response=await post('/checkout',{tier,attemptId:id,termsVersion:terms.version,termsHash:terms.sha256,acceptTerms:true});return {id,response,data:await response.json()};};
 const webhook=async(order,eventId='evt_'+randomUUID(),type='checkout.session.completed')=>{const payload=JSON.stringify({id:eventId,object:'event',type,livemode:false,data:{object:{id:'cs_test_'+order}}});const signature=Stripe.webhooks.generateTestHeaderString({payload,secret});return api.fetch(endpoint+'/stripe/webhook',{method:'POST',headers:{'Stripe-Signature':signature},body:payload});};
 return {mf,db,api,post,checkout,webhook,requests,sent,setFailEmails:n=>{failEmails=n;}};
}
async function withFixture(fn,bindings={},session={}) {const f=await fixture(bindings,session);try{await fn(f);}finally{await f.mf.dispose();}}
test('missing approved terms closes checkout without a Stripe request',()=>withFixture(async f=>{const r=await f.checkout();assert.equal(r.response.status,503);assert.equal(f.requests.length,0);},{TERMS_JSON:'{}'}));
test('live mode requires separate explicit activation',()=>withFixture(async f=>{const r=await f.checkout();assert.equal(r.response.status,503);},{MODE:'live',STRIPE_SECRET_KEY:'sk_live_fixture'}));
test('checkout controls product, quantity and redirect and reuses an attempt',()=>withFixture(async f=>{
 const id=randomUUID();const a=await f.checkout('team',id);assert.equal(a.response.status,200);assert.equal(a.data.url.startsWith('https://checkout.stripe.com/'),true);const b=await f.checkout('team',id);assert.equal(b.data.url,a.data.url);const calls=f.requests.filter(x=>x.method==='POST');assert.equal(calls.length,1);assert.equal(calls[0].body.get('line_items[0][price]'),'price_team');assert.equal(calls[0].body.get('line_items[0][quantity]'),'1');assert.equal(calls[0].body.get('success_url'),origin+'/purchase-success.html');
 const rejected=await f.post('/checkout',{tier:'single',attemptId:randomUUID(),termsVersion:terms.version,termsHash:terms.sha256,acceptTerms:true,amount:1});assert.equal(rejected.status,400);
 const stale=await f.post('/checkout',{tier:'single',attemptId:randomUUID(),termsVersion:'stale',termsHash:terms.sha256,acceptTerms:true});assert.equal(stale.status,400);
},{},{payment_status:'unpaid'}));
test('signed paid webhook atomically issues one license under concurrent and distinct events',()=>withFixture(async f=>{
 const {id}=await f.checkout();const responses=await Promise.all([f.webhook(id,'evt_one'),f.webhook(id,'evt_one'),f.webhook(id,'evt_two')]);for(const r of responses)assert.equal(r.status,200);assert.equal((await f.db.prepare('SELECT COUNT(*) AS n FROM licenses').first()).n,1);assert.equal((await f.db.prepare('SELECT COUNT(*) AS n FROM delivery_jobs').first()).n,2);
}));
test('raw signature verification rejects modified and stale bodies',()=>withFixture(async f=>{
 const payload=JSON.stringify({id:'evt_x',type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_test_unknown'}}});let h=Stripe.webhooks.generateTestHeaderString({payload,secret});let r=await f.api.fetch(endpoint+'/stripe/webhook',{method:'POST',headers:{'Stripe-Signature':h},body:payload+' '});assert.equal(r.status,400);
 h=Stripe.webhooks.generateTestHeaderString({payload,secret,timestamp:1});r=await f.api.fetch(endpoint+'/stripe/webhook',{method:'POST',headers:{'Stripe-Signature':h},body:payload});assert.equal(r.status,400);assert.equal(f.requests.length,0);
}));
for(const [name,changes] of [['unpaid',{payment_status:'unpaid'}],['wrong quantity',{line_items:{data:[{quantity:2,price:{id:'price_single',currency:'eur',unit_amount:139900,livemode:false}}],has_more:false}}],['wrong mode',{livemode:true}],['wrong total',{amount_total:1}],['wrong currency',{currency:'usd'}]])test('does not issue for '+name,()=>withFixture(async f=>{const{id}=await f.checkout();const r=await f.webhook(id);assert.equal(r.status,200);assert.equal((await f.db.prepare('SELECT COUNT(*) AS n FROM licenses').first()).n,0);},{},changes));
test('outbox retries failures and produces a Unicode PDF plus receipt',()=>withFixture(async f=>{
 const{id}=await f.checkout();assert.equal((await f.webhook(id)).status,200);f.setFailEmails(1);await f.api.fetch(endpoint+'/__test_delivery');assert.equal((await f.db.prepare("SELECT COUNT(*) AS n FROM delivery_jobs WHERE state='sent'").first()).n,1);await f.db.prepare("UPDATE delivery_jobs SET next_attempt=0 WHERE state='pending'").run();await f.api.fetch(endpoint+'/__test_delivery');assert.equal((await f.db.prepare("SELECT COUNT(*) AS n FROM delivery_jobs WHERE state='sent'").first()).n,2);const buyer=f.sent.find(x=>x.message.to[0]==='buyer@example.com');assert.match(buyer.message.text,/https:\/\/pay.stripe.com\/receipts\/fixture/);const attempts=f.sent.filter(x=>x.message.to[0]==='buyer@example.com');assert.equal(attempts.length,2);assert.equal(attempts[0].key,attempts[1].key);assert.equal(attempts[0].message.attachments[0].content,attempts[1].message.attachments[0].content,'retry must use identical PDF bytes');const bytes=Buffer.from(buyer.message.attachments[0].content,'base64');assert.equal(bytes.subarray(0,4).toString(),'%PDF');await writeFile('/tmp/iolinki-license-test.pdf',bytes);const count=f.sent.length;await f.api.fetch(endpoint+'/__test_delivery');assert.equal(f.sent.length,count);
}));

test('buyer certificate failure does not prevent owner notification',()=>withFixture(async f=>{const{id}=await f.checkout();await f.webhook(id);await f.api.fetch(endpoint+'/__test_delivery');const jobs=(await f.db.prepare('SELECT role,state,last_error FROM delivery_jobs').all()).results;assert.equal(jobs.find(j=>j.role==='buyer').state,'failed');assert.equal(jobs.find(j=>j.role==='owner').state,'sent');assert.equal(f.sent.length,1);},{},{customer_details:{name:'Unsupported 漢字',email:'buyer@example.com'}}));
test('fulfillment transaction rolls back license and jobs on database failure',()=>withFixture(async f=>{const{id}=await f.checkout();await f.db.exec("CREATE TRIGGER block_delivery BEFORE INSERT ON delivery_jobs BEGIN SELECT RAISE(ABORT, 'fixture failure'); END;");assert.equal((await f.webhook(id)).status,503);assert.equal((await f.db.prepare('SELECT COUNT(*) AS n FROM licenses').first()).n,0);assert.equal((await f.db.prepare('SELECT state FROM orders WHERE id=?').bind(id).first()).state,'pending');await f.db.exec('DROP TRIGGER block_delivery;');assert.equal((await f.webhook(id)).status,200);assert.equal((await f.db.prepare('SELECT COUNT(*) AS n FROM licenses').first()).n,1);}));
test('concurrent delivery handlers claim each job once',()=>withFixture(async f=>{const{id}=await f.checkout();await f.webhook(id);await Promise.all([f.api.fetch(endpoint+'/__test_delivery'),f.api.fetch(endpoint+'/__test_delivery')]);assert.equal(f.sent.length,2);assert.equal(new Set(f.sent.map(x=>x.key)).size,2);}));
test('old ambiguous delivery stops before provider idempotency expires',()=>withFixture(async f=>{const{id}=await f.checkout();await f.webhook(id);await f.db.prepare('UPDATE delivery_jobs SET first_attempt=?').bind(Date.now()-24*3600000).run();await f.api.fetch(endpoint+'/__test_delivery');assert.equal(f.sent.length,0);assert.equal((await f.db.prepare("SELECT COUNT(*) AS n FROM delivery_jobs WHERE state='failed'").first()).n,2);}));
test('checkout rejects unaccepted terms and cross-origin requests',()=>withFixture(async f=>{const body={tier:'single',attemptId:randomUUID(),termsVersion:terms.version,termsHash:terms.sha256,acceptTerms:false};assert.equal((await f.post('/checkout',body)).status,400);body.acceptTerms=true;assert.equal((await f.post('/checkout',body,{Origin:'https://evil.example'})).status,403);assert.equal(f.requests.length,0);}));
test('purchase attempts are rate limited before Stripe calls',()=>withFixture(async f=>{for(let i=0;i<10;i++)assert.equal((await f.checkout()).response.status,200);const count=f.requests.length;assert.equal((await f.checkout()).response.status,429);assert.equal(f.requests.length,count);}));
test('paid or quarantined attempts never return a fresh payment URL',()=>withFixture(async f=>{const{id}=await f.checkout();await f.webhook(id);await f.db.prepare('UPDATE orders SET checkout_url=NULL WHERE id=?').bind(id).run();const count=f.requests.length;assert.equal((await f.checkout('single',id)).response.status,409);assert.equal(f.requests.length,count);await f.db.prepare("UPDATE orders SET state='quarantined' WHERE id=?").bind(id).run();assert.equal((await f.checkout('single',id)).response.status,409);}));
test('unresolved attempts stop before Stripe idempotency expiration',()=>withFixture(async f=>{const{id}=await f.checkout();await f.db.prepare('UPDATE orders SET session_id=NULL,checkout_url=NULL,created_at=? WHERE id=?').bind(Date.now()-24*3600000,id).run();const count=f.requests.length;assert.equal((await f.checkout('single',id)).response.status,409);assert.equal(f.requests.length,count);}));

test('checkout never exposes a new URL when its database link is not saved',()=>withFixture(async f=>{await f.db.exec("CREATE TRIGGER block_order_link BEFORE UPDATE OF checkout_url ON orders BEGIN SELECT RAISE(IGNORE); END;");const{id,response}=await f.checkout();assert.equal(response.status,503);assert.equal((await f.db.prepare('SELECT session_id FROM orders WHERE id=?').bind(id).first()).session_id,null);}));
test('recorded open checkout is recovered without another creation',()=>withFixture(async f=>{const{id}=await f.checkout();await f.db.prepare('UPDATE orders SET checkout_url=NULL WHERE id=?').bind(id).run();assert.equal((await f.checkout('single',id)).response.status,200);assert.equal(f.requests.filter(r=>r.method==='POST').length,1);},{},{payment_status:'unpaid'}));
test('expired recorded checkout is rejected without another creation',()=>withFixture(async f=>{const{id}=await f.checkout();assert.equal((await f.checkout('single',id)).response.status,503);assert.equal(f.requests.filter(r=>r.method==='POST').length,1);},{},{status:'expired',payment_status:'unpaid'}));
