import ii from "./callback-ii.wasm";
import iiii from "./callback-iiii.wasm";
import vii from "./callback-vii.wasm";
const bridgeModules={ii,iiii,vii};
async function Module(moduleArg={}){var moduleRtn;var f=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,h=false;if(h){const {createRequire:a}=await ((m)=>import(m))("node:module");var require=a(import.meta.url)}var l=(a,c)=>{throw c;},ca=import.meta.url;
if(h){var fs=require("node:fs");ca.startsWith("file:")&&require("node:path").dirname(require("node:url").fileURLToPath(ca));process.argv.slice(2);l=(a,c)=>{process.exitCode=a;throw c;}}else if(aa||ba)try{new URL(".",ca)}catch{}var da=console.log.bind(console),t=console.error.bind(console),u=!1,w;function ea(a){for(var c=0,b=a.length,d=new Uint8Array(b),e;c<b;++c)e=a.charCodeAt(c),d[c]=~e>>8&e;return d}var fa,ha,x,y,ia,ja,z,ka,la,ma,na=!1;
function oa(){var a=B.buffer;x=new Int8Array(a);ia=new Int16Array(a);f.HEAPU8=y=new Uint8Array(a);new Uint16Array(a);f.HEAP32=ja=new Int32Array(a);z=new Uint32Array(a);ka=new Float32Array(a);la=new Float64Array(a);ma=new BigInt64Array(a);new BigUint64Array(a)}function C(a){f.onAbort?.(a);a="Aborted("+a+")";t(a);u=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ha?.(a);throw a;}var pa;async function qa(a){return a}
async function ra(a){var c=pa;try{var b=await qa(c);return await WebAssembly.instantiate(b,a)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),C(d)}}async function sa(a){return ra(a)}class ua{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var va=a=>{for(;0<a.length;)a.shift()(f)},wa=[],xa=[],ya=()=>{var a=f.preRun.shift();xa.push(a)},D=!0,za=(a,c)=>{for(var b=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),b++):b&&(a.splice(d,1),b--)}if(c)for(;b;b--)a.unshift("..");return a},Aa=a=>{var c="/"===a.charAt(0),b="/"===a.slice(-1);(a=za(a.split("/").filter(d=>!!d),!c).join("/"))||c||(a=".");a&&b&&(a+="/");return(c?"/":"")+a},Ba=a=>{var c=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=c[0];c=c[1];if(!a&&!c)return".";c&&=c.slice(0,-1);return a+c},Ca=()=>{if(h){var a=require("node:crypto");return c=>a.randomFillSync(c)}return c=>crypto.getRandomValues(c)},Da=a=>{(Da=Ca())(a)},Ea=(...a)=>{for(var c="",b=!1,d=a.length-1;-1<=d&&!b;d--){b=0<=d?a[d]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";c=b+"/"+c;b="/"===b.charAt(0)}c=za(c.split("/").filter(e=>!!e),!b).join("/");return(b?"/":"")+c||"."},Fa=globalThis.TextDecoder&&new TextDecoder,
F=(a,c=0,b,d)=>{var e=c;b=e+b;if(d)d=b;else{for(;a[e]&&!(e>=b);)++e;d=e}if(16<d-c&&a.buffer&&Fa)return Fa.decode(a.subarray(c,d));for(e="";c<d;)if(b=a[c++],b&128){var g=a[c++]&63;if(192==(b&224))e+=String.fromCharCode((b&31)<<6|g);else{var k=a[c++]&63;b=224==(b&240)?(b&15)<<12|g<<6|k:(b&7)<<18|g<<12|k<<6|a[c++]&63;65536>b?e+=String.fromCharCode(b):(b-=65536,e+=String.fromCharCode(55296|b>>10,56320|b&1023))}}else e+=String.fromCharCode(b);return e},Ga=[],Ha=a=>{for(var c=0,b=0;b<a.length;++b){var d=
a.charCodeAt(b);127>=d?c++:2047>=d?c+=2:55296<=d&&57343>=d?(c+=4,++b):c+=3}return c},Ia=(a,c,b,d)=>{if(!(0<d))return 0;var e=b;d=b+d-1;for(var g=0;g<a.length;++g){var k=a.codePointAt(g);if(127>=k){if(b>=d)break;c[b++]=k}else if(2047>=k){if(b+1>=d)break;c[b++]=192|k>>6;c[b++]=128|k&63}else if(65535>=k){if(b+2>=d)break;c[b++]=224|k>>12;c[b++]=128|k>>6&63;c[b++]=128|k&63}else{if(b+3>=d)break;c[b++]=240|k>>18;c[b++]=128|k>>12&63;c[b++]=128|k>>6&63;c[b++]=128|k&63;g++}}c[b]=0;return b-e},Ja=[];
function Ka(a,c){Ja[a]={input:[],output:[],D:c};La(a,Ma)}
var Ma={open(a){var c=Ja[a.node.rdev];if(!c)throw new G(43);a.tty=c;a.seekable=!1},close(a){a.tty.D.fsync(a.tty)},fsync(a){a.tty.D.fsync(a.tty)},read(a,c,b,d){if(!a.tty||!a.tty.D.O)throw new G(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.D.O(a.tty)}catch(n){throw new G(29);}if(void 0===k&&0===e)throw new G(6);if(null===k||void 0===k)break;e++;c[b+g]=k}e&&(a.node.atime=Date.now());return e},write(a,c,b,d){if(!a.tty||!a.tty.D.M)throw new G(60);try{for(var e=0;e<d;e++)a.tty.D.M(a.tty,c[b+e])}catch(g){throw new G(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Na={O(){a:{if(!Ga.length){var a=null;if(h){var c=Buffer.alloc(256),b=0,d=process.stdin.fd;try{b=fs.readSync(d,c,0,256)}catch(e){if(e.toString().includes("EOF"))b=0;else throw e;}0<b&&(a=c.slice(0,b).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}c=Array(Ha(a)+1);a=Ia(a,c,0,c.length);c.length=a;Ga=c}a=Ga.shift()}return a},M(a,c){null===c||10===c?(da(F(a.output)),a.output=
[]):0!=c&&a.output.push(c)},fsync(a){0<a.output?.length&&(da(F(a.output)),a.output=[])},ga(){return{$:25856,ba:5,Z:191,aa:35387,Y:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ha(){return 0},ia(){return[24,80]}},Oa={M(a,c){null===c||10===c?(t(F(a.output)),a.output=[]):0!=c&&a.output.push(c)},fsync(a){0<a.output?.length&&(t(F(a.output)),a.output=[])}},H={s:null,v(){return H.createNode(null,"/",16895,0)},createNode(a,c,b,d){if(24576===(b&61440)||4096===(b&61440))throw new G(63);
H.s||(H.s={dir:{node:{A:H.h.A,u:H.h.u,lookup:H.h.lookup,G:H.h.G,rename:H.h.rename,unlink:H.h.unlink,rmdir:H.h.rmdir,readdir:H.h.readdir,symlink:H.h.symlink},stream:{o:H.l.o}},file:{node:{A:H.h.A,u:H.h.u},stream:{o:H.l.o,read:H.l.read,write:H.l.write,R:H.l.R,T:H.l.T}},link:{node:{A:H.h.A,u:H.h.u,readlink:H.h.readlink},stream:{}},N:{node:{A:H.h.A,u:H.h.u},stream:Pa}});b=Qa(a,c,b,d);16384===(b.mode&61440)?(b.h=H.s.dir.node,b.l=H.s.dir.stream,b.g={}):32768===(b.mode&61440)?(b.h=H.s.file.node,b.l=H.s.file.stream,
b.m=0,b.g=null):40960===(b.mode&61440)?(b.h=H.s.link.node,b.l=H.s.link.stream):8192===(b.mode&61440)&&(b.h=H.s.N.node,b.l=H.s.N.stream);b.atime=b.mtime=b.ctime=Date.now();a&&(a.g[c]=b,a.atime=a.mtime=a.ctime=b.atime);return b},fa(a){return a.g?a.g.subarray?a.g.subarray(0,a.m):new Uint8Array(a.g):new Uint8Array(0)},h:{A(a){var c={};c.dev=8192===(a.mode&61440)?a.id:1;c.ino=a.id;c.mode=a.mode;c.nlink=1;c.uid=0;c.gid=0;c.rdev=a.rdev;16384===(a.mode&61440)?c.size=4096:32768===(a.mode&61440)?c.size=a.m:
40960===(a.mode&61440)?c.size=a.link.length:c.size=0;c.atime=new Date(a.atime);c.mtime=new Date(a.mtime);c.ctime=new Date(a.ctime);c.blksize=4096;c.blocks=Math.ceil(c.size/c.blksize);return c},u(a,c){for(var b of["mode","atime","mtime","ctime"])null!=c[b]&&(a[b]=c[b]);void 0!==c.size&&(c=c.size,a.m!=c&&(0==c?(a.g=null,a.m=0):(b=a.g,a.g=new Uint8Array(c),b&&a.g.set(b.subarray(0,Math.min(c,a.m))),a.m=c)))},lookup(){H.I||(H.I=new G(44),H.I.stack="<generic error, no stack>");throw H.I;},G(a,c,b,d){return H.createNode(a,
c,b,d)},rename(a,c,b){try{var d=I(c,b)}catch(g){}if(d){if(16384===(a.mode&61440))for(var e in d.g)throw new G(55);e=Ra(d.parent.id,d.name);if(J[e]===d)J[e]=d.C;else for(e=J[e];e;){if(e.C===d){e.C=d.C;break}e=e.C}}delete a.parent.g[a.name];c.g[b]=a;a.name=b;c.ctime=c.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,c){delete a.g[c];a.ctime=a.mtime=Date.now()},rmdir(a,c){var b=I(a,c),d;for(d in b.g)throw new G(55);delete a.g[c];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.g)]},
symlink(a,c,b){a=H.createNode(a,c,41471,0);a.link=b;return a},readlink(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},l:{read(a,c,b,d,e){var g=a.node.g;if(e>=a.node.m)return 0;a=Math.min(a.node.m-e,d);if(8<a&&g.subarray)c.set(g.subarray(e,e+a),b);else for(d=0;d<a;d++)c[b+d]=g[e+d];return a},write(a,c,b,d,e,g){c.buffer===x.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(c.subarray&&(!a.g||a.g.subarray)){if(g)return a.g=c.subarray(b,b+d),a.m=d;if(0===a.m&&0===e)return a.g=
c.slice(b,b+d),a.m=d;if(e+d<=a.m)return a.g.set(c.subarray(b,b+d),e),d}g=e+d;var k=a.g?a.g.length:0;k>=g||(g=Math.max(g,k*(1048576>k?2:1.125)>>>0),0!=k&&(g=Math.max(g,256)),k=a.g,a.g=new Uint8Array(g),0<a.m&&a.g.set(k.subarray(0,a.m),0));if(a.g.subarray&&c.subarray)a.g.set(c.subarray(b,b+d),e);else for(g=0;g<d;g++)a.g[e+g]=c[b+g];a.m=Math.max(a.m,e+d);return d},o(a,c,b){1===b?c+=a.position:2===b&&32768===(a.node.mode&61440)&&(c+=a.node.m);if(0>c)throw new G(28);return c},R(a,c,b,d,e){if(32768!==(a.node.mode&
61440))throw new G(43);a=a.node.g;if(e&2||!a||a.buffer!==x.buffer){d=!0;C();e=void 0;if(!e)throw new G(48);if(a){if(0<b||b+c<a.length)a.subarray?a=a.subarray(b,b+c):a=Array.prototype.slice.call(a,b,b+c);x.set(a,e)}}else d=!1,e=a.byteOffset;return{ka:e,X:d}},T(a,c,b,d){H.l.write(a,c,0,d,b,!1);return 0}}},Sa=(a,c)=>{var b=0;a&&(b|=365);c&&(b|=146);return b},Ta=null,Ua={},K=[],Va=1,J=null,Wa=!1,Xa=!0,G=class{name="ErrnoError";constructor(a){this.B=a}},Ya=class{F={};node=null;get flags(){return this.F.flags}set flags(a){this.F.flags=
a}get position(){return this.F.position}set position(a){this.F.position=a}},Za=class{h={};l={};H=null;constructor(a,c,b,d){a||=this;this.parent=a;this.v=a.v;this.id=Va++;this.name=c;this.mode=b;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function L(a,c={}){if(!a)throw new G(44);c.K??(c.K=!0);"/"===a.charAt(0)||(a="//"+a);var b=0;a:for(;40>b;b++){a=a.split("/").filter(n=>!!n);for(var d=Ta,e="/",g=0;g<a.length;g++){var k=g===a.length-1;if(k&&c.parent)break;if("."!==a[g])if(".."===a[g])if(e=Ba(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");b--;continue a}else d=d.parent;else{e=Aa(e+"/"+a[g]);try{d=I(d,a[g])}catch(n){if(44===n?.B&&k&&c.V)return{path:e};throw n;}!d.H||k&&!c.K||(d=d.H.root);if(40960===(d.mode&61440)&&(!k||c.J)){if(!d.h.readlink)throw new G(52);
d=d.h.readlink(d);"/"===d.charAt(0)||(d=Ba(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new G(32);}function Ra(a,c){for(var b=0,d=0;d<c.length;d++)b=(b<<5)-b+c.charCodeAt(d)|0;return(a+b>>>0)%J.length}function I(a,c){var b=16384===(a.mode&61440)?(b=M(a,"x"))?b:a.h.lookup?0:2:54;if(b)throw new G(b);for(b=J[Ra(a.id,c)];b;b=b.C){var d=b.name;if(b.parent.id===a.id&&d===c)return b}return a.h.lookup(a,c)}
function Qa(a,c,b,d){a=new Za(a,c,b,d);c=Ra(a.parent.id,a.name);a.C=J[c];return J[c]=a}function M(a,c){return Xa?0:c.includes("r")&&!(a.mode&292)||c.includes("w")&&!(a.mode&146)||c.includes("x")&&!(a.mode&73)?2:0}function $a(a,c){if(16384!==(a.mode&61440))return 54;try{return I(a,c),20}catch(b){}return M(a,"wx")}function N(a){a=K[a];if(!a)throw new G(8);return a}function ab(a,c=-1){a=Object.assign(new Ya,a);if(-1==c)a:{for(c=0;4096>=c;c++)if(!K[c])break a;throw new G(33);}a.fd=c;return K[c]=a}
function bb(a,c){var b=null?.l.u,d=b?null:a;b??=a.h.u;if(!b)throw new G(63);b(d,c)}var Pa={open(a){a.l=Ua[a.node.rdev].l;a.l.open?.(a)},o(){throw new G(70);}};function La(a,c){Ua[a]={l:c}}function cb(a,c){var b="/"===c;if(b&&Ta)throw new G(10);if(!b&&c){var d=L(c,{K:!1});c=d.path;d=d.node;if(d.H)throw new G(10);if(16384!==(d.mode&61440))throw new G(54);}c={type:a,ja:{},S:c,U:[]};a=a.v(c);a.v=c;c.root=a;b?Ta=a:d&&(d.H=c,d.v&&d.v.U.push(c))}
function db(a,c,b){var d=L(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new G(28);if("."===a||".."===a)throw new G(20);var e=$a(d,a);if(e)throw new G(e);if(!d.h.G)throw new G(63);return d.h.G(d,a,c,b)}function R(a){return db(a,16895,0)}function eb(a,c,b){"undefined"==typeof b&&(b=c,c=438);db(a,c|8192,b)}
function fb(a,c){if(!Ea(a))throw new G(44);var b=L(c,{parent:!0}).node;if(!b)throw new G(44);c=c&&c.match(/([^\/]+|\/)\/*$/)[1];var d=$a(b,c);if(d)throw new G(d);if(!b.h.symlink)throw new G(63);b.h.symlink(b,c,a)}
function gb(a,c,b=438){if(""===a)throw new G(44);if("string"==typeof c){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[c];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${c}`);c=d}b=c&64?b&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var g=L(a,{J:!(c&131072),V:!0});d=g.node;a=g.path}g=!1;if(c&64)if(d){if(c&128)throw new G(20);}else{if(e)throw new G(31);d=db(a,b|511,0);g=!0}if(!d)throw new G(44);8192===(d.mode&61440)&&(c&=-513);if(c&65536&&16384!==(d.mode&61440))throw new G(54);
if(!g&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][c&3],c&512&&(e+="w"),e=16384===(d.mode&61440)&&("r"!==e||c&576)?31:M(d,e)):e=44,e))throw new G(e);if(c&512&&!g){e=d;e="string"==typeof e?L(e,{J:!0}).node:e;if(16384===(e.mode&61440))throw new G(31);if(32768!==(e.mode&61440))throw new G(28);if(a=M(e,"w"))throw new G(a);bb(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.v.S;var k=k?"/"!==e[e.length-1]?`${e}/${k}`:e+k:e;break a}k=k?`${e.name}/${k}`:e.name;e=e.parent}c=ab({node:d,
path:k,flags:c&-131713,seekable:!0,position:0,l:d.l,W:[],error:!1});c.l.open&&c.l.open(c);g&&(b&=511,d="string"==typeof d?L(d,{J:!0}).node:d,bb(d,{mode:b&4095|d.mode&-4096,ctime:Date.now(),da:void 0}));return c}function hb(a,c,b){if(null===a.fd)throw new G(8);if(!a.seekable||!a.l.o)throw new G(70);if(0!=b&&1!=b&&2!=b)throw new G(28);a.position=a.l.o(a,c,b);a.W=[]}
function S(a,c,b){a=Aa("/dev/"+a);var d=Sa(!!c,!!b);S.P??(S.P=64);var e=S.P++<<8|0;La(e,{open(g){g.seekable=!1},close(){b?.buffer?.length&&b(10)},read(g,k,n,p){for(var m=0,A=0;A<p;A++){try{var q=c()}catch(r){throw new G(29);}if(void 0===q&&0===m)throw new G(6);if(null===q||void 0===q)break;m++;k[n+A]=q}m&&(g.node.atime=Date.now());return m},write(g,k,n,p){for(var m=0;m<p;m++)try{b(k[n+m])}catch(A){throw new G(29);}p&&(g.node.mtime=g.node.ctime=Date.now());return m}});eb(a,d,e)}
for(var T={},ib=void 0,jb=0,U={},kb=a=>{w=a;D||0<jb||(f.onExit?.(a),u=!0);l(a,new ua(a))},lb=a=>{if(!u)try{a()}catch(c){c instanceof ua||"unwind"==c||l(1,c)}finally{if(!(D||0<jb))try{w=a=w,kb(a)}catch(c){c instanceof ua||"unwind"==c||l(1,c)}}},V=[],mb=a=>{var c=V[a];c||(V[a]=c=W.get(a));return c},X,nb=[],ob=a=>{const c=a.length;return[c%128|128,c>>7,...a]},pb={i:127,p:127,j:126,f:125,d:124,e:111},qb=a=>ob(Array.from(a,c=>pb[c])),Y=new Uint8Array(123),Z=25;0<=Z;--Z)Y[48+Z]=52+Z,Y[65+Z]=Z,Y[97+Z]=26+
Z;Y[43]=62;Y[47]=63;J=Array(4096);cb(H,"/");R("/tmp");R("/home");R("/home/web_user");(function(){R("/dev");La(259,{read:()=>0,write:(d,e,g,k)=>k,o:()=>0});eb("/dev/null",259);Ka(1280,Na);Ka(1536,Oa);eb("/dev/tty",1280);eb("/dev/tty1",1536);var a=new Uint8Array(1024),c=0,b=()=>{0===c&&(Da(a),c=a.byteLength);return a[--c]};S("random",b);S("urandom",b);R("/dev/shm");R("/dev/shm/tmp")})();
(function(){R("/proc");var a=R("/proc/self");R("/proc/self/fd");cb({v(){var c=Qa(a,"fd",16895,73);c.l={o:H.l.o};c.h={lookup(b,d){b=+d;var e=N(b);b={parent:null,v:{S:"fake"},h:{readlink:()=>e.path},id:b+1};return b.parent=b},readdir(){return Array.from(K.entries()).filter(([,b])=>b).map(([b])=>b.toString())}};return c}},"/proc/self/fd")})();f.noExitRuntime&&(D=f.noExitRuntime);f.print&&(da=f.print);f.printErr&&(t=f.printErr);
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
f.addFunction=(a,c)=>{if(!X){X=new WeakMap;var b=W.length;if(X)for(var d=0;d<0+b;d++){var e=mb(d);e&&X.set(e,d)}}if(b=X.get(a)||0)return b;b=nb.length?nb.pop():W.grow(1);try{W.set(b,a),V[b]=W.get(b)}catch(g){if(!(g instanceof TypeError))throw g;c=bridgeModules[c];if(!c)throw Error("Unsupported callback signature");c=(new WebAssembly.Instance(c,{e:{f:a}})).exports.f;W.set(b,c);V[b]=W.get(b)}X.set(a,b);return b};
f.removeFunction=a=>{X.delete(mb(a));W.set(a,null);V[a]=W.get(a);nb.push(a)};f.getValue=function(a,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":return x[a];case "i8":return x[a];case "i16":return ia[a>>1];case "i32":return ja[a>>2];case "i64":return ma[a>>3];case "float":return ka[a>>2];case "double":return la[a>>3];case "*":return z[a>>2];default:C(`invalid type for getValue: ${c}`)}};f.UTF8ToString=(a,c,b)=>a?F(y,a,c,b):"";f.stringToUTF8=(a,c,b)=>Ia(a,y,c,b);f.lengthBytesUTF8=Ha;
var rb,B,W,sb={__syscall_dup:function(a){try{var c=N(a),b=ab(c,-1);b.l?.ea?.(b);return b.fd}catch(d){if("undefined"==typeof T||"ErrnoError"!==d.name)throw d;return-d.B}},__syscall_openat:function(a,c,b,d){ib=d;try{c=c?F(y,c):"";var e=c;if("/"===e.charAt(0))c=e;else{var g=-100===a?"/":N(a).path;if(0==e.length)throw new G(44);c=g+"/"+e}if(d){var k=ja[+ib>>2];ib+=4;var n=k}else n=0;return gb(c,b,n).fd}catch(p){if("undefined"==typeof T||"ErrnoError"!==p.name)throw p;return-p.B}},_abort_js:()=>C(""),_emscripten_runtime_keepalive_clear:()=>
{D=!1;jb=0},_setitimer_js:(a,c)=>{U[a]&&(clearTimeout(U[a].id),delete U[a]);if(!c)return 0;var b=setTimeout(()=>{delete U[a];lb(()=>rb(a,performance.now()))},c);U[a]={id:b,la:c};return 0},emscripten_date_now:()=>Date.now(),emscripten_resize_heap:a=>{var c=y.length;a>>>=0;if(2147483648<a)return!1;for(var b=1;4>=b;b*=2){var d=c*(1+.2/b);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(d);oa();var e=1;break a}catch(g){}e=
void 0}if(e)return!0}return!1},exit:a=>{w=a;kb(a)},fd_close:function(a){try{var c=N(a);if(null===c.fd)throw new G(8);c.L&&(c.L=null);try{c.l.close&&c.l.close(c)}catch(b){throw b;}finally{K[c.fd]=null}c.fd=null;return 0}catch(b){if("undefined"==typeof T||"ErrnoError"!==b.name)throw b;return b.B}},fd_read:function(a,c,b,d){try{a:{var e=N(a);a=c;for(var g,k=c=0;k<b;k++){var n=z[a>>2],p=z[a+4>>2];a+=8;var m=e,A=n,q=p,r=g,ta=x;if(0>q||0>r)throw new G(28);if(null===m.fd)throw new G(8);if(1===(m.flags&2097155))throw new G(8);
if(16384===(m.node.mode&61440))throw new G(31);if(!m.l.read)throw new G(28);var O="undefined"!=typeof r;if(!O)r=m.position;else if(!m.seekable)throw new G(70);var P=m.l.read(m,ta,A,q,r);O||(m.position+=P);var v=P;if(0>v){var Q=-1;break a}c+=v;if(v<p)break;"undefined"!=typeof g&&(g+=v)}Q=c}z[d>>2]=Q;return 0}catch(E){if("undefined"==typeof T||"ErrnoError"!==E.name)throw E;return E.B}},fd_seek:function(a,c,b,d){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);try{if(isNaN(c))return 61;var e=
N(a);hb(e,c,b);ma[d>>3]=BigInt(e.position);e.L&&0===c&&0===b&&(e.L=null);return 0}catch(g){if("undefined"==typeof T||"ErrnoError"!==g.name)throw g;return g.B}},fd_write:function(a,c,b,d){try{a:{var e=N(a);a=c;for(var g,k=c=0;k<b;k++){var n=z[a>>2],p=z[a+4>>2];a+=8;var m=e,A=n,q=p,r=g,ta=x;if(0>q||0>r)throw new G(28);if(null===m.fd)throw new G(8);if(0===(m.flags&2097155))throw new G(8);if(16384===(m.node.mode&61440))throw new G(31);if(!m.l.write)throw new G(28);m.seekable&&m.flags&1024&&hb(m,0,2);
var O="undefined"!=typeof r;if(!O)r=m.position;else if(!m.seekable)throw new G(70);var P=m.l.write(m,ta,A,q,r,void 0);O||(m.position+=P);var v=P;if(0>v){var Q=-1;break a}c+=v;if(v<p)break;"undefined"!=typeof g&&(g+=v)}Q=c}z[d>>2]=Q;return 0}catch(E){if("undefined"==typeof T||"ErrnoError"!==E.name)throw E;return E.B}},proc_exit:kb},tb;
tb=await (async function(){function a(b){b=tb=b.exports;f._xmlResetLastError=b.xmlResetLastError;f._xmlGetLastError=b.xmlGetLastError;f._xmlCtxtParseDtd=b.xmlCtxtParseDtd;f._xmlCtxtReadMemory=b.xmlCtxtReadMemory;f._xmlCtxtSetErrorHandler=b.xmlCtxtSetErrorHandler;f._xmlNewInputFromMemory=b.xmlNewInputFromMemory;f._xmlFreeParserCtxt=b.xmlFreeParserCtxt;f._xmlNewParserCtxt=b.xmlNewParserCtxt;f._xmlInitParser=b.xmlInitParser;f._xmlNewNs=b.xmlNewNs;f._xmlSetNs=b.xmlSetNs;f._xmlFreeDtd=b.xmlFreeDtd;
f._xmlFreeNode=b.xmlFreeNode;f._xmlGetIntSubset=b.xmlGetIntSubset;f._xmlNewDoc=b.xmlNewDoc;f._xmlFreeDoc=b.xmlFreeDoc;f._xmlRemoveProp=b.xmlRemoveProp;f._xmlNewNode=b.xmlNewNode;f._xmlNewDocNode=b.xmlNewDocNode;f._xmlNewReference=b.xmlNewReference;f._xmlNewDocTextLen=b.xmlNewDocTextLen;f._xmlNewCDataBlock=b.xmlNewCDataBlock;f._xmlNewDocComment=b.xmlNewDocComment;f._xmlAddNextSibling=b.xmlAddNextSibling;f._xmlAddPrevSibling=b.xmlAddPrevSibling;f._xmlAddChild=b.xmlAddChild;f._xmlUnlinkNode=b.xmlUnlinkNode;
f._xmlNodeGetContent=b.xmlNodeGetContent;f._xmlGetNodePath=b.xmlGetNodePath;f._xmlDocGetRootElement=b.xmlDocGetRootElement;f._xmlDocSetRootElement=b.xmlDocSetRootElement;f._xmlSetNsProp=b.xmlSetNsProp;f._xmlNodeSetContentLen=b.xmlNodeSetContentLen;f._xmlGetNsList=b.xmlGetNsList;f._xmlSearchNs=b.xmlSearchNs;f._xmlHasNsProp=b.xmlHasNsProp;f._xmlSetWinPathEnabled=b.xmlSetWinPathEnabled;f._xmlCtxtValidateDtd=b.xmlCtxtValidateDtd;f._xmlOutputBufferClose=b.xmlOutputBufferClose;f._xmlOutputBufferCreateIO=
b.xmlOutputBufferCreateIO;f._xmlRegisterInputCallbacks=b.xmlRegisterInputCallbacks;f._xmlCleanupInputCallbacks=b.xmlCleanupInputCallbacks;f._xmlC14NExecute=b.xmlC14NExecute;f._xmlSaveSetIndentString=b.xmlSaveSetIndentString;f._xmlSaveToIO=b.xmlSaveToIO;f._xmlSaveDoc=b.xmlSaveDoc;f._xmlSaveTree=b.xmlSaveTree;f._xmlSaveClose=b.xmlSaveClose;f._xmlRelaxNGFree=b.xmlRelaxNGFree;f._xmlRelaxNGNewDocParserCtxt=b.xmlRelaxNGNewDocParserCtxt;f._xmlRelaxNGFreeParserCtxt=b.xmlRelaxNGFreeParserCtxt;f._xmlRelaxNGParse=
b.xmlRelaxNGParse;f._xmlRelaxNGSetParserStructuredErrors=b.xmlRelaxNGSetParserStructuredErrors;f._xmlRelaxNGNewValidCtxt=b.xmlRelaxNGNewValidCtxt;f._xmlRelaxNGFreeValidCtxt=b.xmlRelaxNGFreeValidCtxt;f._xmlRelaxNGSetValidStructuredErrors=b.xmlRelaxNGSetValidStructuredErrors;f._xmlRelaxNGValidateDoc=b.xmlRelaxNGValidateDoc;f._xmlSchemaFree=b.xmlSchemaFree;f._xmlSchemaNewDocParserCtxt=b.xmlSchemaNewDocParserCtxt;f._xmlSchemaFreeParserCtxt=b.xmlSchemaFreeParserCtxt;f._xmlSchemaFreeValidCtxt=b.xmlSchemaFreeValidCtxt;
f._xmlSchemaParse=b.xmlSchemaParse;f._xmlSchemaSetParserStructuredErrors=b.xmlSchemaSetParserStructuredErrors;f._xmlSchemaSetValidStructuredErrors=b.xmlSchemaSetValidStructuredErrors;f._xmlSchemaNewValidCtxt=b.xmlSchemaNewValidCtxt;f._xmlSchemaValidateOneElement=b.xmlSchemaValidateOneElement;f._xmlSchemaValidateDoc=b.xmlSchemaValidateDoc;f._xmlXIncludeNewContext=b.xmlXIncludeNewContext;f._xmlXIncludeFreeContext=b.xmlXIncludeFreeContext;f._xmlXIncludeSetErrorHandler=b.xmlXIncludeSetErrorHandler;f._xmlXIncludeProcessNode=
b.xmlXIncludeProcessNode;f._xmlXPathFreeCompExpr=b.xmlXPathFreeCompExpr;f._xmlXPathFreeObject=b.xmlXPathFreeObject;f._xmlXPathRegisterNs=b.xmlXPathRegisterNs;f._xmlXPathNewContext=b.xmlXPathNewContext;f._xmlXPathFreeContext=b.xmlXPathFreeContext;f._xmlXPathCtxtCompile=b.xmlXPathCtxtCompile;f._xmlXPathCompiledEval=b.xmlXPathCompiledEval;f._xmlXPathSetContextNode=b.xmlXPathSetContextNode;rb=b._emscripten_timeout;f._malloc=b.malloc;f._free=b.free;B=b.memory;W=b.__indirect_function_table;oa();return tb}
var c={env:sb,wasi_snapshot_preview1:sb};if(f.instantiateWasm)return new Promise(b=>{f.instantiateWasm(c,(d,e)=>{b(a(d,e))})});throw Error('Static WASM initializer is required');return a((await sa(c)).instance)}());
(function(){function a(){f.calledRun=!0;if(!u){na=!0;if(!f.noFSInit&&!Wa){var c,b;Wa=!0;c??=f.stdin;b??=f.stdout;d??=f.stderr;c?S("stdin",c):fb("/dev/tty","/dev/stdin");b?S("stdout",null,b):fb("/dev/tty","/dev/stdout");d?S("stderr",null,d):fb("/dev/tty1","/dev/stderr");gb("/dev/stdin",0);gb("/dev/stdout",1);gb("/dev/stderr",1)}tb.__wasm_call_ctors();Xa=!1;fa?.(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var d=f.postRun.shift();
wa.push(d)}va(wa)}}if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();va(xa);f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()})();na?moduleRtn=f:moduleRtn=new Promise((a,c)=>{fa=a;ha=c});
;return moduleRtn}export default Module;
