#!/usr/bin/env node
"use strict";

// Generates the files the studio, the ChatGPT widget, and the MCP server load.
// Sources: library/*.json, engine.js, station_view.js, widget.js, widget.css.
//   library/browser_data.js            filed library for the web page
//   widget.html                        self-contained ChatGPT widget
//   ../tools/iodd/station.generated.mjs  engine + library + widget for the MCP
// `node studio/build.js --check` fails when a generated file is stale.

const fs = require("node:fs");
const path = require("node:path");

const here = __dirname;
const read = (file) => fs.readFileSync(path.join(here, file), "utf8");

function loadLibrary() {
  const folder = path.join(here, "library/sensors");
  const defs = fs.readdirSync(folder).filter((name) => name.endsWith(".json")).sort().map((name) => JSON.parse(fs.readFileSync(path.join(folder, name), "utf8")));
  // Datasheet power figures, kept apart so each value carries its own source.
  const powerFile = path.join(here, "library/power.json");
  const power = fs.existsSync(powerFile) ? JSON.parse(fs.readFileSync(powerFile, "utf8")) : {};
  defs.forEach((def) => {
    if (power[def.id]) {
      def.power = power[def.id];
    }
  });
  return {
    sensors: defs.filter((def) => def.kind === "sensor"),
    masters: defs.filter((def) => def.kind === "master"),
    equipment: JSON.parse(read("library/equipment.json")),
    applications: JSON.parse(read("library/applications.json")),
  };
}

function outputs() {
  const library = JSON.stringify(loadLibrary());
  const browserData = "window.IOLINKI_LIBRARY = " + library + ";\n";
  // three.js r158 (MIT, vendor/three.LICENSE) is inlined so the widget needs no CDN.
  const scripts = [browserData, read("vendor/three.min.js"), read("engine.js"), read("station_3d.js"), read("station_tables.js"), read("widget.js")].join("\n").replace(/<\/script/gi, "<\\/script");
  const widget = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\" />\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n<title>iolinki station</title>\n<style>\n" + read("widget.css") + "</style>\n</head>\n<body>\n<div id=\"root\"></div>\n<script>\n" + scripts + "</script>\n</body>\n</html>\n";
  const module = "// Generated by studio/build.js. Do not edit.\n" +
    "const module = { exports: {} };\n" + read("engine.js") + "\n" +
    "export const engine = module.exports;\n" +
    "export const LIBRARY = " + library + ";\n" +
    "export const WIDGET_HTML = " + JSON.stringify(widget) + ";\n";
  return {
    "library/browser_data.js": browserData,
    "widget.html": widget,
    "../tools/iodd/station.generated.mjs": module,
  };
}

const check = process.argv.includes("--check");
let stale = [];
Object.entries(outputs()).forEach(([file, text]) => {
  const target = path.join(here, file);
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
  if (current === text) {
    return;
  }
  if (check) {
    stale.push(file);
  } else {
    fs.writeFileSync(target, text);
    console.log("wrote", file);
  }
});
if (stale.length) {
  console.error("stale, run node studio/build.js:", stale.join(", "));
  process.exit(1);
}
